### ISSUE TITLE
F-droid distribution?

### ISSUE THREAD

**Issue by rpdelaney** [supertorpe/chessendgametraining#1]
Some folks (incl. me) don't like using Google services like the Play store. FOSS apps can be distributed to weirdos like me via [F-droid.org](https://f-droid.org/en/docs/FAQ_-_App_Developers/). Would you consider including it there, if it meets the [inclusion criteria](https://f-droid.org/en/docs/Inclusion_Policy/)?

**Comment by supertorpe** [comment]
I was considering it, but the f-droid workflow is not very friendly with cordova apps. I have to review it again, and see if there have been changes in this regard. Meanwhile, you can download the apk from the releases tab.

**Comment by supertorpe** [comment]
You can also use the online version: https://chess-endgame-trainer.web.app
It is a PWA webapp so you can install it and even use it offline.

**Comment by supertorpe** [comment]
Since there is an alternative method of installing the app (PWA install), not relying on Google Play Store, I'm not going to publish it on F-Droid.
