### ISSUE TITLE
Duplicated endgame position

### ISSUE THREAD

**Issue by Nicals** [supertorpe/chessendgametraining#13]
Those two endgames are identical:

  + https://chess-endgame-trainer.firebaseapp.com/position/1/1/0
  + https://chess-endgame-trainer.firebaseapp.com/position/1/1/2

**Comment by supertorpe** [comment]
Thanks for reporting! It will be fixed in the next release.

**Comment by supertorpe** [comment]
Fixed in v3 branch (already published in [https://chess-endgame-trainer.[firebaseapp.com|web.app]](https://chess-endgame-trainer.[firebaseapp.com|web.app]/))
