### ISSUE TITLE
Magic wand result doesn't display optimal number of moves

### ISSUE THREAD

**Issue by aspiers** [supertorpe/chessendgametraining#16]
After tapping the magic wand, an optimal sequence is shown, but at the end it just says "Checkmate".  It would be more helpful to also show how many moves were taken.

**Comment by supertorpe** [comment]
Yes, I have to add a moves count indicator.

**Comment by supertorpe** [comment]
Fixed in v3 branch (already published in [https://chess-endgame-trainer.[firebaseapp.com|web.app]](https://chess-endgame-trainer.[firebaseapp.com|web.app]/)). You can see the list of moves.
