### ISSUE TITLE
Tap squares to move pieces

### ISSUE THREAD

**Issue by jmanuelbr** [supertorpe/chessendgametraining#2]
It would be great if I could move the pieces by tapping the piece and then taping again the destination square, as opposed to drag and drop it. It would be more usable for mobile devices. E.g.
- Queen is on a1 and I want to move it to d3 
- Tap on a1
- Tap on d3
- Queen moves to d3

Some other mobile app applications work like this E.g. Lichess I personally find it easier to use.

**Comment by supertorpe** [comment]
The mobile app allows you to move the pieces in both ways.

**Comment by supertorpe** [comment]
I've released the patch; now you can move the pieces tapping in a mobile browser: https://chess-endgame-trainer.web.app
