### ISSUE TITLE
threefold repetition

### ISSUE THREAD

**Issue by Jonathan003** [supertorpe/chessendgametraining#20]
I really like your app to train chess endgames.
I have some request for future updates.

I would like to be able take back the moves after threefold repetitions or stalemate and go one with the exercise. Now I can take back the moves after a threefold repetitions or stalemate but I can not continue the exercise.

Also if I try to take back the move before the stalemate and I copy the position to continue the exercise for example in droidfish the position that is copied is not the position before the stalemate but the position with the stalemate.

I hope you can fix this.

**Comment by supertorpe** [comment]
Thinking about a button "Continue from here" (to play the current position) while in review mode.

Copy position to clipboard already fixed in commit e9fdda68219cbafa4a22cdd4f86ba3ea582774ac
It will promote in the next release.

**Comment by supertorpe** [comment]
Fixed in v3 branch (already published in [https://chess-endgame-trainer.[firebaseapp.com|web.app]](https://chess-endgame-trainer.[firebaseapp.com|web.app]/)). Now you can click on a previous move and go on from there, creating another line of moves.

**Comment by Jonathan003** [comment]
Thanks for the fix!
