### ISSUE TITLE
forward/back icons are wrong way around

### ISSUE THREAD

**Issue by aspiers** [supertorpe/chessendgametraining#21]
Going from left to right there are five icons:

1. icon A (double left chevron), currently meaning "go to beginning position"
2. icon B (single left chevron with a vertical line), currently meaning "go back one ply"
3. icon C, currently meaning "auto play"
4. icon D (single right chevron with a vertical line), currently meaning "go forward one ply"
4. icon E (double right chevron), currently meaning "go to final position"

but while the *behaviour* is ordered correctly, visually the icons A and B are the wrong way around, as are D and E.  The conventional meaning of these icons is that the vertical line signifies a hard stop at the beginning or end.  So the leftmost should be icon B meaning "go to beginning position", then icon A meaning "go back one ply", and similarly for D/E.

**Comment by supertorpe** [comment]
Oh! my poor UX/UI skills. I'll change the icons...

**Comment by aspiers** [comment]
Thanks! ;-)

**Comment by supertorpe** [comment]
Fixed in v3 branch (already published in [https://chess-endgame-trainer.[firebaseapp.com|web.app]](https://chess-endgame-trainer.[firebaseapp.com|web.app]/)): navigation is no longer with buttons but clicking on the move list

**Comment by supertorpe** [comment]
Fixed in v3 branch (already published in [https://chess-endgame-trainer.[firebaseapp.com|web.app]](https://chess-endgame-trainer.[firebaseapp.com%7Cweb.app]/)): navigation is no longer with buttons but clicking on the move list
