### ISSUE TITLE
copy complete pgn

### ISSUE THREAD

**Issue by Jonathan003** [supertorpe/chessendgametraining#22]
I also have another request. I'm studying 2 knight versus pawn endgames which are very tricky I think. I like the option with the magic stick to query syzigy endgame tablebases. I would like to be able to copy the complete pgn (afterwards), and not only the position. So I can train it wit chess position trainer or chessable for example.

Regards Jonathan

**Comment by supertorpe** [comment]
I will break down the "copy" icon in two icons: "copy FEN" and "copy PGN"

**Comment by supertorpe** [comment]
Fixed in the latest commit of the v3 branch. It's available online: https://chess-endgame-trainer.web.app
