### ISSUE TITLE
2 pawns vs 2 pawn

### ISSUE THREAD

**Issue by khoramshahi** [supertorpe/chessendgametraining#23]
First, I want to thank you for this great tool.
I regularly use it to train for pawn endgames.

I noticed that we don't have section for 2 pawns vs 2 pawns. 
If I provide a fen database would be interested to add them?

Moreover, can we have more refine subcategories: for example we can have  categorization from Averbakh's book for "two pawns against one" (connected pawns, isolated pawns, and double pawns)

**Comment by supertorpe** [comment]
Hi Mahdi, I appreciate your comments, I'm glad you use the application and find it useful.
I will be happy to receive new positions (FEN) to add to the database. However, I would not want to copy copyrighted material to avoid possible legal problems.
Creating sub-sub-categories at the moment would complicate navigation and the UI in general, but I could think of some way to add a descriptive tag to each position.
Thanks for the suggestions

**Comment by khoramshahi** [comment]
Hi,

I was thinking to provide fen for positions from Aberbakh 4th volume.
I don't know how the copyright works here (for a fen position) since even Averbakh is presenting the positions while mentioning the source, mostly coming from Grigoriev. 


At least the fen position can be sorted based on the sub-sub-category.

**Comment by supertorpe** [comment]
I am not a lawyer, but from what I have been reading, individual positions would not be protected by copyright, but the compilation would be. I suppose that including some positions in the database should not be problematic, as long as it is not a significant amount of the same book.

**Comment by supertorpe** [comment]
Since importing endgame databases provided by users is in the roadmap for version 4.0.0, I'm closing this issue.
