### ISSUE TITLE
King + Knight + Bishop vs King mate not in the database?

### ISSUE THREAD

**Issue by indaleciourceyra** [supertorpe/chessendgametraining#26]
Really great app--I'm finding it very useful. There is quite a list of Knight and Bishop endings, but the mate itself is missing, which is a pity.

**Comment by PiR43** [comment]
I think you want this page : https://chess-endgame-trainer.web.app/list/3/2. The King + Knight + Bishop vs King mate  are present but not in "Knight + Bishop" section but in "Knight" section perhaps better to move this ?
