### ISSUE TITLE
Mistake for position/1/4/5 ?

### ISSUE THREAD

**Issue by PiR43** [supertorpe/chessendgametraining#28]
It seems this problem has no solution: https://chess-endgame-trainer.web.app/position/1/4/5
Perhaps not a checkmate but a draw ?

**Comment by j-krl** [comment]
There's quite a few problems where the hint gives unfeasible mate. Looks like the issue is bigger than just one problem.

**Comment by supertorpe** [comment]
The positions were obtained from a database with the target of each position (draw or mate).
It appears that this database is not 100% reliable. Therefore, I started to develop a program to verify each and every one of the positions (against tablebases when possible, and with stockfish in all other cases) to check: 1) if the target should be draw or mate and 2) the minimum number of movements required to achieve the target.

**Comment by supertorpe** [comment]
Position updated as "draw"
