### ISSUE TITLE
King and Pawn endgames

### ISSUE THREAD

**Issue by maldoinc** [supertorpe/chessendgametraining#37]
Hi all.

For the King and Pawn endgames do you think the goal could be changed from checkmating to promotion(Perhaps even as an option)? It feels repetitive to have to checkmate the enemy King with the newly promoted Queen/Rook. Besides, problems for K + Q/R vs K already exist.

**Comment by Alayan-stk-2** [comment]
This is the biggest downside of the endgame trainer. It wastes a lot of time to have to do a basic Q/R checkmate to complete a pawn exercise. Reaching a won KQvK or KRvK position would be a better endpoint for these exercises.

**Comment by supertorpe** [comment]
Fixed in v3 branch (already published in https://chess-endgame-trainer.[firebaseapp.com|web.app])
