### ISSUE TITLE
Consider using stockfish.js from npm

### ISSUE THREAD

**Issue by niklasf** [supertorpe/chessendgametraining#4]
A while ago I started publishing stockfish.js on npm, to make it easier for Lichess to follow (ornicar/lila@1ef896e5d9750ab1beaef6e5730924031ae25b88): https://www.npmjs.com/package/stockfish.js

You could consider also getting it from there, instead of bundling it in the repo.

**Comment by supertorpe** [comment]
Yes, you are quite right, much better to get the dependence from npm. I will change this.
Thanks for the info.

**Comment by supertorpe** [comment]
Done.
