### ISSUE TITLE
Bug in transition to EGTB

### ISSUE THREAD

**Issue by Alayan-stk-2** [supertorpe/chessendgametraining#69]
https://chess-endgame-trainer.firebaseapp.com/position/1/5/0

The start position is 6K1/5p2/5Pk1/6p1/3pP1P1/8/8/8 w - - 0 1 ; 8-men

White plays e5, e5, exf7. with this capture, it becomes a 7-men TB position. Instead of recognizing the move as correct (all the others draw), the website displays an error, an "unfeasible mate" message, and black plays a nonsensical Kh6 move allowing a trivial mate in 2;

**Comment by supertorpe** [comment]
Fixed in v3 branch (already published in https://chess-endgame-trainer.[firebaseapp.com|web.app])
