### ISSUE TITLE
Navigation buttons to browse the games in web app.

### ISSUE THREAD

**Issue by Jonathan003** [supertorpe/chessendgametraining#76]
If I use chessendgametrainer in the web app on my Windows pc in Google Chrome, there are not back and forwards buttons, to browse true the games. I have to click on the move numbers to go back and forwards.
I would like to have navigation buttons like in the Android app of chessendgame trainer.

**Comment by supertorpe** [comment]
Maybe I could add a navigation toolbar on medium-big screens (in mobile it takes valuable space from the move list).

**Comment by Jonathan003** [comment]
I would be nice if you could bring back this functionality for bigger screens. Because I miss these navigation buttons. Also for my Samsung S22+ which have a relatively big screen size of 6.6-inch.

**Comment by Jonathan003** [comment]
https://github.com/supertorpe/chessendgametraining/assets/40061628/74d63c91-4084-47b0-9388-d5f5668fcdf3

**Comment by supertorpe** [comment]
I mean, in some mobile devices it doesn't have much room for the move list. In an iPhone SE, it can barely fit 5 moves:

![chess-endgame-trainer mooo com_(iPhone SE)](https://github.com/supertorpe/chessendgametraining/assets/1201504/990be41d-12f3-4cd3-a427-ba9b8335949f)

If I put a button toolbar between the board and the list It will make it even smaller, and for the sake to navigate clicking buttons when there is already possible to navigate by clicking on the moves from the list.

I'll have to take a decission about this.

**Comment by Jonathan003** [comment]
Maybe you can just ad an option for navigation buttons. That you can enable or disable like desired.

**Comment by supertorpe** [comment]
Done in v3.0.19
