### ISSUE TITLE
A way to play against black to move positions while still playing white

### ISSUE THREAD

**Issue by ssmythe** [supertorpe/chessendgametraining#77]
In Dvoretsky's Endgame manual, 5th ed, position 1-1:

Black to move: 8/3k4/8/3K4/3P4/8/8/8 b - - 0 1
https://chess-endgame-trainer.mooo.com/fen/8/3k4/8/3K4/3P4/8/8/8%20b%20-%20-%200%201

White to move: 8/3k4/8/3K4/3P4/8/8/8 w - - 0 1
https://chess-endgame-trainer.mooo.com/fen/8/3k4/8/3K4/3P4/8/8/8%20w%20-%20-%200%201

It would be nice to have a way to have the engine play as black and the human as white, with the board orientation as white.

Maybe a flip board, or play position as white button that would put it into this mode?  Something in the settings menu?

**Comment by supertorpe** [comment]
Do you mean, have a button to change roles? Maybe it would be useful for some particular positions.
The moment you moved a piece with roles changed in a position from the database, the result shouldn't get saved.
"Flip board" is only a visual change. The button should change the FEN's piece turn ("w" <=> "b").
I have to think when the app will let you press that button, and the effects it would cause: only in a clean position, or also when you have made some moves?

**Comment by ssmythe** [comment]
URL parameters would be a practical solution. Here’s how it can be applied to the examples provided:

Example A: Black to Move

The original FEN indicates it's black's turn to move:

Original Position:  
Black to move: 8/3k4/8/3K4/3P4/8/8/8 b - - 0 1  
https://chess-endgame-trainer.mooo.com/fen/8/3k4/8/3K4/3P4/8/8/8%20b%20-%20-%200%201

To change the roles so the human plays as white, and the computer plays as black with the board oriented for white, the URL could be modified as follows:

Modified URL:  
https://chess-endgame-trainer.mooo.com/fen/8/3k4/8/3K4/3P4/8/8/8%20b%20-%20-%200%201?h=w&c=b&o=w

In this setup:
- The human plays white.
- The computer plays black.
- The board is oriented with white at the bottom.

This allows white to play for a win, with the computer making the first move.

Example B: White to Move

The original FEN indicates it's white's turn to move:

Original Position:  
White to move: 8/3k4/8/3K4/3P4/8/8/8 w - - 0 1  
Link: https://chess-endgame-trainer.mooo.com/fen/8/3k4/8/3K4/3P4/8/8/8%20w%20-%20-%200%201

In this position, white plays for a draw. The current functionality is adequate for this scenario.

Summary

Using URL parameters to define roles and board orientation allows the FEN and board state to remain consistent while specifying:
- Who plays which side (h=w for human as white, c=b for computer as black)
- Board orientation (o=w for white orientation)

This approach ensures flexibility without altering the fundamental position or FEN string, making it easier for users to customize their experience based on their needs.

**Comment by ssmythe** [comment]
Excellent.  Thank you for the change.  This should work out great!  I look forward to be able to try it out.

**Comment by supertorpe** [comment]
v3.0.7 published: https://chess-endgame-trainer.mooo.com/fen/8/3k4/8/3K4/3P4/8/8/8%20w%20-%20-%200%201?player=b

**Comment by ssmythe** [comment]
If you use https://chess-endgame-trainer.mooo.com/fen/8/3k4/8/3K4/3P4/8/8/8%20b%20-%20-%200%201?player=w the computer does in fact make the first move.  Great job!  This is perfect!
