### ISSUE TITLE
problem running chessendgametraining app in Windows Subsystem For Android

### ISSUE THREAD

**Issue by Jonathan003** [supertorpe/chessendgametraining#78]
Because there are no navigation buttons in the web app. (I already made an issue about this problem a few months ago but I didn't get a reply).
I tried to install and run the apk file in Windows Subsystem For Android.
I was able to install the app but I can't run it.
I have made a video capture of it.
I like to work with my big screen on Windows computer.
On my Samsung phone the screen is to small, and I don't use my Android tablet allot.
I know I can cast my Android screen to my Windows pc with scrcpy+
But that's a lot of work.

https://github.com/supertorpe/chessendgametraining/assets/40061628/e40dd146-fdb6-49c0-9aaa-e3aab64eef04

**Comment by supertorpe** [comment]
You can run the webapp directly in the browser: https://chess-endgame-trainer.mooo.com/
It's a PWA so you can even "install" it clicking this icon in your browser's navigation bar:
![image](https://github.com/supertorpe/chessendgametraining/assets/1201504/9d35db4c-9987-492b-9569-581ca77830ba)

**Comment by Jonathan003** [comment]
I just notice it is not possible to navigate the game (with back and forth buttons) also in the Android app. I think this was possible with older versions of the app.
Can you bring back this functionality please? 
I know I can copy the game and analyse it in Lichess (or any other chess app), that way.
But I would like to have some back and forth navigation button in the chessendgametrainer app also. Bothe for the Android app as for the browser app.
