### ISSUE TITLE
Some puzzles with wrong targets

### ISSUE THREAD

**Issue by berger1920** [supertorpe/chessendgametraining#8]
Hello,

There are a few minor errors in some problems...

1) Instead of "white to checkmate" it should say "black to checkmate":
Basic -> Pawn 2/7 -> Problem 100
Basic -> Pawn 2/7 -> Problem 112

2) It's White's move, and they have to checkmate... but they only have the King!  :)
Basic -> Pawn 3/7 -> Problem 12

Regards,
Berger

**Comment by supertorpe** [comment]
Thank you for reporting. I will prepare a patch for the next release to correct these puzzles.

**Comment by supertorpe** [comment]
Fixed
