### ISSUE TITLE
Wrong unfeasible mate messages

### ISSUE THREAD

**Issue by JuergenWetzel** [supertorpe/chessendgametraining#82]
In at least one situation, I get the message "unfeasible mate" incorrect. In my case, it's in 2P vs. P #85 (I'm black). I made one move for the computer 1. ... Kc4 2. Kf5 because I wasn't sure how to continue in this position. When I play 2. ... Kd4 it responses 3. e5 and I get the incorrect message, I get that after 3. fxe5 again, Lichess says there mate in 10.
I'm not sure if it's because I made one move for the computer and switched after that back to computer makes the move or if the calculations are bugged

**Comment by supertorpe** [comment]
Thanks for reporting. Fixed in https://github.com/supertorpe/chessendgametraining/commit/324df48eacda1e3651d05309c933402eafc8bb4a
