### ISSUE TITLE
Add "position to clipboard" option

### ISSUE THREAD

**Issue by berger1920** [supertorpe/chessendgametraining#9]
Hello,

It would be nice to have the option of exporting the position of the board to the clipboard at any time, in FEN notation. Sometimes it is interesting to be able to analyze a certain position. For example, I like to use DroidFish because of the way it shows the analysis on the board, and it has the "Paste Position" option.

Thank you!  :)

Regards,
Berger

**Comment by supertorpe** [comment]
Done
